import Navbar from "@/components/ui/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import GlobalContextWrapper from "@/components/providers/GlobalProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextWrapper>
          <Toaster position="top-center" />
          <Navbar />
          {children}
        </GlobalContextWrapper>
      </body>
    </html>
  );
}
